package ingest

import (
	"strings"
	"testing"
)

func TestCleanPromptStripsHarnessBlocks(t *testing.T) {
	in := "<system-reminder>do not mention this</system-reminder>\nFix the cart drawer"
	if got := CleanPrompt(in); got != "Fix the cart drawer" {
		t.Fatalf("CleanPrompt = %q", got)
	}
}

func TestCleanPromptHandlesNestedBlocks(t *testing.T) {
	// A <rules> block contains <context> subsections. A non-greedy pattern
	// would stop at the inner closing tag and leave the outer tail behind.
	in := "<rules><context>stuff</context>more rules</rules>\nwhat should we build?"
	got := CleanPrompt(in)
	if strings.Contains(got, "rules") || strings.Contains(got, "stuff") {
		t.Fatalf("CleanPrompt left harness content: %q", got)
	}
	if got != "what should we build?" {
		t.Fatalf("CleanPrompt = %q", got)
	}
}

func TestCleanPromptDropsUnclosedBlock(t *testing.T) {
	in := "<environment_details>truncated dump that never closes"
	if got := CleanPrompt(in); got != "" {
		t.Fatalf("CleanPrompt = %q, want empty for a truncated dump", got)
	}
}

func TestCleanPromptUnwrapsUserQuery(t *testing.T) {
	in := "<timestamp>Tue</timestamp>\n<user_query>\nupdate the hero copy\n</user_query>"
	if got := CleanPrompt(in); got != "update the hero copy" {
		t.Fatalf("CleanPrompt = %q", got)
	}
}

func TestCleanPromptRejectsSyntheticRecords(t *testing.T) {
	in := "Caveat: The messages below were generated by the user while running local commands."
	if got := CleanPrompt(in); got != "" {
		t.Fatalf("CleanPrompt = %q, want empty", got)
	}
}

func TestCleanPromptKeepsCustomElementsInProse(t *testing.T) {
	// The unknown-block stripper only fires at the very start of a prompt, so
	// markup discussed mid-sentence survives.
	in := "the layout breaks when <my-widget> is nested"
	if got := CleanPrompt(in); got != in {
		t.Fatalf("CleanPrompt rewrote prose: %q", got)
	}
}

func TestExtractSkillRefs(t *testing.T) {
	refs, cleaned := ExtractSkillRefs("read ${HOME}/.claude/skills/storefront-verify/SKILL.md then run it")
	if len(refs) != 1 || refs[0] != "storefront-verify" {
		t.Fatalf("refs = %v", refs)
	}
	if strings.Contains(cleaned, "skills") || strings.Contains(cleaned, "claude") {
		t.Fatalf("cleaned still names the path: %q", cleaned)
	}
}

func TestExtractSkillRefsFromAnnouncement(t *testing.T) {
	refs, _ := ExtractSkillRefs("Using the superpowers:brainstorming skill to plan")
	if len(refs) != 1 || refs[0] != "brainstorming" {
		t.Fatalf("refs = %v, want [brainstorming]", refs)
	}
}

func TestIsPromptLike(t *testing.T) {
	if IsPromptLike("yes") {
		t.Fatal("a two-word ack should not read as an intent")
	}
	if !IsPromptLike("deploy the storefront theme") {
		t.Fatal("a real request should read as an intent")
	}
}

func TestGistDropsCodeFences(t *testing.T) {
	in := "```diff\n- old\n+ new\n```\nmake the header sticky"
	if got := Gist(in, 80); got != "make the header sticky" {
		t.Fatalf("Gist = %q", got)
	}
}

func TestRepairMojibake(t *testing.T) {
	broken := mis("\u2014")
	got := repairMojibake(byteOrderMark + "# /storefront-verify " + broken + " prove what went live works")
	want := "# /storefront-verify \u2014 prove what went live works"
	if got != want {
		t.Fatalf("repairMojibake = %q, want %q", got, want)
	}
}

func TestRepairMojibakeLeavesOrdinaryTextAlone(t *testing.T) {
	in := "d\u00e9j\u00e0 vu \u2014 na\u00efve caf\u00e9"
	if got := repairMojibake(in); got != in {
		t.Fatalf("repairMojibake rewrote valid text: %q", got)
	}
}

func TestSlashCommandBecomesTheIntent(t *testing.T) {
	in := "<command-name>/eod</command-name>\n<command-message>eod</command-message>\n<command-args>for today</command-args>"
	got := CleanPrompt(in)
	if got != "/eod for today" {
		t.Fatalf("CleanPrompt = %q, want the command as the intent", got)
	}
}

func TestBuiltinSlashCommandsAreNotIntents(t *testing.T) {
	for _, name := range []string{"/model", "/clear", "/compact"} {
		in := "<command-name>" + name + "</command-name><command-args></command-args>"
		if got := CleanPrompt(in); got != "" {
			t.Errorf("CleanPrompt(%q) = %q, want empty: a client setting is not work", name, got)
		}
	}
}

func TestPluginQualifiedCommandKeepsItsOwnName(t *testing.T) {
	name, _, ok := SlashCommand("<command-name>/superpowers:brainstorming</command-name>")
	if !ok || name != "brainstorming" {
		t.Fatalf("SlashCommand = %q ok=%v", name, ok)
	}
}
